####################################################
# Production Org Jobs
# All deployment jobs for the production environment.
# Set PRODUCTION_ORG_URL, PRODUCTION_AUTH_URL as CI/CD variables in your project.
####################################################

test:predeploy:prd:
  extends: .validate-metadata
  stage: test
  resource_group: production
  rules:
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == 'develop' || $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == 'fullqa' || $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == $CI_DEFAULT_BRANCH
      when: never
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
      when: manual
  allow_failure: false
  variables:
    AUTH_ALIAS: PRODUCTION
    AUTH_URL: $PRODUCTION_AUTH_URL
  environment:
    name: validate-production
    url: $PRODUCTION_ORG_URL

deploy:prd:
  extends: .deploy-metadata
  stage: deploy
  resource_group: production
  rules:
    - if: $PRODUCTION_DISABLED
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /chore\(metadata-retrieval\):/i'
      when: never
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == 'push'
      when: always
  allow_failure: false
  variables:
    AUTH_ALIAS: PRODUCTION
    AUTH_URL: $PRODUCTION_AUTH_URL
  environment:
    name: production
    url: $PRODUCTION_ORG_URL

destroy:prd:
  extends: .delete-metadata
  stage: destroy
  resource_group: production
  rules:
    - if: $PRODUCTION_DISABLED
      when: never
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == 'web' && $PACKAGE
      when: always
  allow_failure: false
  variables:
    AUTH_ALIAS: PRODUCTION
    AUTH_URL: $PRODUCTION_AUTH_URL
  environment:
    name: production
    url: $PRODUCTION_ORG_URL

destroy:prd:push:
  extends: .delete-metadata-push
  stage: destroy
  resource_group: production
  rules:
    - if: $PRODUCTION_DISABLED
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /chore\(metadata-retrieval\):/i'
      when: never
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == 'push'
      when: always
  allow_failure: true
  variables:
    AUTH_ALIAS: PRODUCTION
    AUTH_URL: $PRODUCTION_AUTH_URL
  environment:
    name: production
    url: $PRODUCTION_ORG_URL

merge:prd:
  extends: .auto-merge
  stage: merge
  resource_group: merge-prd
  needs: []
  rules:
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == 'develop' || $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == 'fullqa'
      when: never
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
      when: manual
  allow_failure: false
  environment:
    name: production
    url: $PRODUCTION_ORG_URL
